# bookmarks list
# thumbnail threads
# thumbnail cache dir
# video thumbnail dir
# default sort mode
# saved sort mode per folder (store in a different file?)
# imgui themes

bookmarks:
 - D:\demez_archive\media\downloads\art
 - D:\demez_archive\media\downloads\animation
 - D:\demez_archive\media\downloads
 - D:\demez_archive\media\demez\drawings
 - D:\demez_archive\phone\sync6

# Amount of threads to use for generating thumbnails, also uses more memory
thumbnail-threads: 8

# Max amount of thumbnails you can upload at a time, this blocks the main thread for a second to upload, so don't set this number too high
thumbnail-uploads-per-frame: 16
thumbnail-cache-path: $app_path$/thumbnail_cache
# thumbnail-video-cache-path: $app_path$/thumbnail_video_cache
thumbnail-video-cache-path: R:\media_tag_system\thumbnail_video_cache
thumbnail-memory-cache-size: 20000

# 0 for immediate updates, 1 for vsync, -1 for adaptive vsync
vsync: 1

